#!/bin/bash

HERE="$(readlink -f "${0%/*}")"
HERE="${HERE%/bin}"
EXTRAS=()
ORIG_CONFIG="$HOME/.config/dataplane-broker/server.properties"
CONFIG="$ORIG_CONFIG"
unset LOG_CONFIG
unset USMUX
unset ASSERT

while [ $# -gt  0 ] ; do
    arg="$1"
    shift

    case "$arg" in
	(-L)
	    EXTRAS+=(-L"$1")
	    shift
	    ;;
	(-L*)
	    EXTRAS+=("$arg")
	    ;;
	(-l)
	    EXTRAS+=(-l"$1")
	    shift
	    ;;
	(-l*)
	    EXTRAS+=("$arg")
	    ;;
	(-ea)
	    ASSERT=1
	    ;;
	(+ea)
	    unset ASSERT
	    ;;
	(--log=*)
	    LOG_CONFIG="$arg"
	    shift
	(-s)
	    USMUX="$1"
	    shift
	    ;;
	(-f)
	    CONFIG="$1"
	    shift
	    ;;
	(-h|--help)
	    cat <<EOF
Usage: $0 [options]
       -Ldir	Append dir to jar search path.
       -lname	Search for name.jar in jar search path, and append to
       		classpath.
       -s addr	Specify the Usmux configuration string.
       -f file	Specify the agent configuration file.
       	  	Default: $ORIG_CONFIG
       -ea      Enable Java assertions.
       --log=file
        	Specify Java logging configuration
EOF
	    exit
	    ;;
	(-*)
	    printf >&2 '%s: unknown switch %s\n' "$0" "$arg"
	    exit 1
	    ;;
	(+*)
	    printf >&2 '%s: unknown switch %s\n' "$0" "$arg"
	    exit 1
	    ;;
	(*)
	    printf >&2 '%s: unknown argument %s\n' "$0" "$arg"
	    exit 1
	    ;;
    esac
done

if [ -z "$USMUX" ] ; then
    printf >&2 '%s: specify -s usmuxconf\n' "$0"
    exit 1
fi

exec jrun "${EXTRAS[@]}" \
     -lusmux_session -lusmux_server -lusmux_unix -ljavax.json \
     -L"$HERE/share/java" -linitiate-dpb-core -linitiate-dpb-util \
     -linitiate-dpb-openflow -linitiate-dpb-corsa \
     ${LOG_CONFIG+-Djava.util.logging.config.file="$LOG_CONFIG"} \
     -Dprogram.name="$0" -Dusmux.config="$USMUX" \
     -Dnetwork.config.server="$CONFIG" ${ASSERT:+-ea} \
     uk.ac.lancs.networks.apps.NetworkServer
