#!/bin/bash

HERE="$(readlink -f "${0%/*}")"
HERE="${HERE%/bin}"
EXTRAS=()
ORIG_CONFIG="$HOME/.config/dataplane-broker/client.properties"
CONFIG="$ORIG_CONFIG"
ARGS=()
unset LOG_CONFIG

while [ $# -gt  0 ] ; do
    arg="$1"
    shift

    case "$arg" in
	(-L)
	    EXTRAS+=(-L"$1")
	    shift
	    ;;
	(-L*)
	    EXTRAS+=("$arg")
	    ;;
	(-l)
	    EXTRAS+=(-l"$1")
	    shift
	    ;;
	(-l*)
	    EXTRAS+=("$arg")
	    ;;
	(-d)
	    LOG_CONFIG="$1"
	    shift
	    ;;
	(-f)
	    CONFIG="$1"
	    shift
	    ;;
	(-h|--help)
	    cat <<EOF
Usage: $0 [options] [commands]
       -Ldir	Append dir to jar search path.
       -lname	Search for name.jar in jar search path, and append to
       		classpath.
       -d file  Specify Java logging configuration
       -f file	Specify the agent configuration file.
       	  	Default: $ORIG_CONFIG
For commands, see:
<http://scc-forge.lancaster.ac.uk/javadoc/dataplanebroker-test/uk/ac/
lancs/networks/apps/Commander-method-main/1java$lang$String>.
EOF
	    exit
	    ;;
	(*)
	    ARGS=("$arg" "$@")
	    break
	    ;;
    esac
done

exec jrun "${EXTRAS[@]}" -ljavax.json \
     -L"$HERE/share/java" -linitiate-dpb-core -linitiate-dpb-util \
     -linitiate-dpb-openflow -linitiate-dpb-corsa \
     ${LOG_CONFIG+-Djava.util.logging.config.file="$LOG_CONFIG"} \
     -Dprogram.name="$0" -Dnetwork.config.client="$CONFIG" \
     uk.ac.lancs.networks.apps.Commander "${ARGS[@]}"
